server:
  port: 5000
  forward-headers-strategy: framework

spring:
  config:
    import: optional:env[.env]

  datasource:
    url: jdbc:mysql://chconewdb.c7c0ii84ukar.ap-northeast-2.rds.amazonaws.com:3306/chocoworld?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: chocoworld
    password: chocoworld
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "http://deploy-choco-env.eba-b8zehrbx.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/google"

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "http://deploy-choco-env.eba-b8zehrbx.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/naver"
            scope:
              - name
              - email
            client-name: Naver

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://deploy-choco-env.eba-b8zehrbx.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

security:
  jwt:
    token:
      expire-length: 14400000 # 4시간

jwt:
  issuer: ajufresh@gmail.com
  secret_key: ${JWT_SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: meltique-bucket
    region:
      static: ap-northeast-2

  stack:
    auto: false

portone:
  imp:
    api-key: ${IMP_API_KEY}
    api-secret: ${IMP_API_SECRET}

custom:
  oauth2:
    redirect-uri: http://deploy-choco-env.eba-b8zehrbx.ap-northeast-2.elasticbeanstalk.com/oauth2/redirect
